server.port: 0

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:      
      defaultZone: ${discountms.eureka.url:http://localhost:8761/eureka}   
      
spring:
  cloud:
    bus:
      enabled: true
      destination: configXchangebus
    stream:
      bindings:
        webaudit-out:
          destination: webaudit
          group: audit
                  
  rabbitmq:
    host: ${rabbitmq.host:192.168.99.100}
    port: ${rabbitmq.port:5672}    
    
  zipkin:
    base-url: ${zipkin.url:http://192.168.99.100:9411}
    enabled: true
  