spring:
  mvc:
    view:
      prefix: /
      suffix: .html

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:demoDb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver

greetProp: ${defaultgreeting} 

management:
  endpoints:
    web:
      exposure:
        include: '*'