management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: ${productms.datasource.url}
    username: ${productms.datasource.username}
    password: ${productms.datasource.password:}
    driver-class-name: ${productms.datasource.driver}
  jpa:
    show-sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:      
      defaultZone: ${productms.eureka.url:http://localhost:8761/eureka}  

server.port: 8080
           