management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: ${productms.datasource.url}
    username: ${productms.datasource.username}
    password: ${productms.datasource.password:}
    driver-class-name: ${productms.datasource.driver}
  jpa:
    show-sql: true

  rabbitmq:
    host: ${rabbitmq.host:192.168.99.100}
    port:  ${rabbitmq.port:5672}
  cloud:
    bus:
      enabled: true
      destination: configXchangebus
  zipkin:
    base-url: ${zipkin.url:http://192.168.99.100:9411}
    enabled: true
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:      
      defaultZone: ${productms.eureka.url:http://192.168.99.100:8761/eureka}


      
feign:
  hystrix:
    enabled: true  

server.port: 8080
           