management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: ${productms.datasource.url}
    username: ${productms.datasource.username}
    password: ${productms.datasource.password}
    driver-class-name: ${productms.datasource.driver:org.h2.Driver}
  jpa:
    show-sql: true